### ISSUE TITLE
Your token is on github

### ISSUE THREAD

**Issue by modelmat** [wntjq6902/discord-gif-compressing-bot#3]
. This allows anybody to sign in with your bot and do bad stuff

**Comment by wntjq6902** [comment]
[https://github.com/wntjq6902/discord-gif-compressing-bot/commit/dfb36c401b17b4f814655124e046a2c6bebd8108](https://github.com/wntjq6902/discord-gif-compressing-bot/commit/dfb36c401b17b4f814655124e046a2c6bebd8108)
